name: Custom Rucio Images Build and Push

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push rucio-dev
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: dev
          file: dev/Dockerfile
          tags: jguiang/rucio-dev:latest

      - name: Build and push rucio-fts
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: fts
          file: fts/Dockerfile
          tags: jguiang/fts:latest
